### ISSUE TITLE
Causes gnome-shell 3.16 to temporarily stop responding on first power button event.

### ISSUE THREAD

**Issue by hashstat** [eonpatapon/gnome-shell-extension-caffeine#48] opened 2015-06-02 08:39 UTC
This is a fantastic extension. I have it on all my Linux systems. Thank you for all your hard work.

After upgrading my Arch systems to gnome-shell 3.16, the first press of the power button causes gnome-shell to become unresponsive for about 25 seconds before finally displaying the Gnome power-off dialog. If the Cancel button is clicked once the power-off dialog appears and then the power button is once again pressed, the power-off dialog appears almost instantly. But after rebooting, the delay from power button press to showing the power-off dialog returns. It may also be forced by disabling the extension, restarting gnome, and re-enabling the extension.

I searched through the code, but I'm not a Gome developer, and so am not sure what is causing the issue.

**Comment by Bujiraso** [comment] 2015-06-07 19:35
I've encountered similar problems to this. 
Continuing forward, I'll be exploring what enabling and disabling the extension does with respect to this bug.

**Comment by cyberalex4life** [comment] 2015-08-16 18:08
I can confirm the problem with power button on Manjaro Gnome 3.16, but more to that, when activating Caffeine the power setting Settings -> Power -> Suspend & Power Off -> When battery power is critical ----goes-----> to Power Off, with no posibility to change it than to deactivate Caffeine by click.

**Comment by cyberalex4life** [comment] 2015-10-16 18:05
is it possible to enable hibernate while blocking screen lock?

**Comment by Bujiraso** [comment] 2016-03-14 19:23
I've taken the logs from `journalctl -xb` for a few days, as this has been happening to me at every shutdown and here are tiny snippets of the log lines that seem relevant:

[20160310 caffeine errors.txt](https://github.com/eonpatapon/gnome-shell-extension-caffeine/files/172720/20160310.caffeine.errors.txt)
[20160313 caffeine errors.txt](https://github.com/eonpatapon/gnome-shell-extension-caffeine/files/172722/20160313.caffeine.errors.txt)
[20160313 caffeine errors 2.txt](https://github.com/eonpatapon/gnome-shell-extension-caffeine/files/172721/20160313.caffeine.errors.2.txt)

**Comment by Poultryphile** [comment] 2016-06-08 03:52
I am experiencing this same issue with Gnome 3.20 on Arch.

**Comment by postblue** [comment] 2016-07-20 16:46
Recently published, the [Keep Awake](https://github.com/jenspfahl/KeepAwake) extension don't have this problem. Maybe a way to find a workaround?

**Comment by eonpatapon** [comment] 2016-07-22 09:06
I couldn't reproduce on my laptop using 3.20.1 on Arch

**Comment by Bujiraso** [comment] 2016-07-23 02:51
@eonpatapon I find it happens more often when I run things full-screen that automatically trigger caffeine.
Can others please say how often they are affected? I don't think it has ever been a 100% for me, more like 50% of the time.

**Comment by Poultryphile** [comment] 2016-07-31 23:59
@eonpatapon I have also noted this to be an intermittently occurring issue.

**Comment by eonpatapon** [comment] 2016-08-30 12:23
Do you have multiple applications that enable caffeine, or do you activate it manually ?

**Comment by Bujiraso** [comment] 2016-08-31 22:21
Multiple applications enable caffeine automatically (full-screen YouTube & various video games), but I occasionally turn it on manually.

**Comment by ogjerstad** [comment] 2016-10-13 19:43
This happens everytime for me, totally reproduceable, no matter if it has been enabled or not. Fedora 24.

**Comment by cyberalex4life** [comment] 2016-10-13 21:32
It has an option to enable it on full-screen applications, you can disable this. However I gave up on it, since I would allways keep it on, with resource consumption and disabling hibernate on low battery. I have just done the right  power Settings , and I am good.

**Comment by klingtnet** [comment] 2016-12-23 10:17
The problem still exists for Gnome 3.22 on Arch Linux. Here are the logs of `journalctl -fxb` when I opened the power off dialog for the first time:

```
Dez 23 11:12:12 elitebook gnome-session[1400]: gnome-session-binary[1400]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Dez 23 11:12:12 elitebook gnome-session[1400]: gnome-session-binary[1400]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Dez 23 11:12:12 elitebook gnome-session[1400]: gnome-session-binary[1400]: WARNING: Client '/org/gnome/SessionManager/Client8' failed to reply before timeout
Dez 23 11:12:12 elitebook gnome-session[1400]: gnome-session-binary[1400]: WARNING: Client '/org/gnome/SessionManager/Client7' failed to reply before timeout
Dez 23 11:12:12 elitebook gnome-session[1400]: gnome-session-binary[1400]: WARNING: Client '/org/gnome/SessionManager/Client6' failed to reply before timeout
Dez 23 11:12:12 elitebook gnome-session-binary[1400]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Dez 23 11:12:12 elitebook gnome-session[1400]: gnome-session-binary[1400]: WARNING: Client '/org/gnome/SessionManager/Client2' failed to reply before timeout
Dez 23 11:12:12 elitebook gnome-session[1400]: gnome-session-binary[1400]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Dez 23 11:12:12 elitebook gnome-session-binary[1400]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Dez 23 11:12:12 elitebook gnome-session-binary[1400]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Dez 23 11:12:12 elitebook gnome-session-binary[1400]: WARNING: Client '/org/gnome/SessionManager/Client8' failed to reply before timeout
Dez 23 11:12:12 elitebook gnome-settings-[1569]: Error setting property 'PowerSaveMode' on interface org.gnome.Mutter.DisplayConfig: Timeout was reached (g-io-error-quark, 24)
Dez 23 11:12:12 elitebook gnome-session-binary[1400]: WARNING: Client '/org/gnome/SessionManager/Client7' failed to reply before timeout
Dez 23 11:12:12 elitebook gnome-session-binary[1400]: WARNING: Client '/org/gnome/SessionManager/Client6' failed to reply before timeout
Dez 23 11:12:12 elitebook gnome-session-binary[1400]: WARNING: Client '/org/gnome/SessionManager/Client2' failed to reply before timeout
Dez 23 11:12:12 elitebook gnome-session-binary[1400]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Dez 23 11:12:12 elitebook gnome-session-binary[1400]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Dez 23 11:12:12 elitebook gnome-session-binary[1400]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Dez 23 11:12:12 elitebook gnome-shell[1418]: JS LOG: Ignored exception from dbus method: Gio.IOErrorEnum: Timeout was reached
Dez 23 11:12:12 elitebook gnome-shell[1418]: JS LOG: gnome-session gave us a dead inhibitor: /org/gnome/SessionManager/Inhibitor2
Dez 23 11:12:14 elitebook gnome-session-binary[1400]: Entering running state
```

Most of the log entries are noise but `Dez 23 11:12:12 elitebook gnome-settings-[1569]: Error setting property 'PowerSaveMode' on interface org.gnome.Mutter.DisplayConfig: Timeout was reached (g-io-error-quark, 24)` seems to be relevant.

**Comment by blasmat** [comment] 2017-01-12 15:26
This occurs every time on both Manjaro and Antergos.

**Comment by goarano** [comment] 2017-01-20 00:02
I have the same issue on fedora 25 with wayland

**Comment by hexvar** [comment] 2017-01-25 08:47
I've got this bug for years. the extension is useful but I'm going to remove it ultil this issue is solved. It's more than one year, ridiculous

**Comment by eonpatapon** [comment] 2017-01-25 09:02
@hexvar please propose a patch, that would be a less ridiculous comment

**Comment by hexvar** [comment] 2017-01-25 09:39
@eonpatapon I'm sorry. it seemed like there wasn't any active development. I'll look into it.

**Comment by eonpatapon** [comment] 2017-01-25 09:41
I've looked at it a bit, but I have no clue where is the issue...

**Comment by hexvar** [comment] 2017-01-25 09:43
we should try to identify which is the problem selectively disabling bits of code. or doing a proper debug.

**Comment by hexvar** [comment] 2017-01-25 09:45
before yesterday I thought it was gnome's (or arch) fault of this behaviour.

**Comment by samupl** [comment] 2017-05-24 14:41
Pretty much the same happens to me on Fedora 25 and X.org

**Comment by Bujiraso** [comment] 2017-05-26 00:25
This was referenced in a KeePassXC bug, I use KeePass. Is there someone experiencing this who does not use it? Just want to discount some weird interaction here.

**Comment by cyberalex4life** [comment] 2017-05-26 07:12
I confirm I am not using KeePassXC. I am on OpenSuSE Leap 42.2 and the problem happens here too. In fact this is a problem of Gnome Shell in general, it does not matter the distro. 

I suspect the "guilt" goes  down on dbus. Dbus has been slow for me when responding to gsetting commands (when enabling/disabling touchpad) and Keep awake! (https://extensions.gnome.org/extension/1097/keep-awake/) similar extension makes GS restart when toggling state very quicly.

I think the blocking is actually a delay in the extension attempting to connect for first time. The blocking disappears after some serious number of waiting (I usually keep pressing Super). I don't know what could be done.

PS: I am not the developer, my opinion is purely based on my experience over time with GNU/Linux

**Comment by Enigma0** [comment] 2017-06-01 00:46
Wasn't sure where this issue originated but I'm having it also.

**Comment by amontalenti** [comment] 2017-06-19 19:53
Happens for me on Ubuntu GNOME 17.04, relatively fresh installation. I also notice that when the logoff dialog finally appears, I also see a notification as if caffeine got activated by the logoff action. Strange bug. Had to disable caffeine for now, as a result.

**Comment by T-ii** [comment] 2017-07-11 06:39
I've noticed this for a week or so on my Arch install with Gnome 3.24.2 and the caffeine extension.

**Comment by legluondunet** [comment] 2017-08-13 08:41
Why this issue closed? The bug is still here in Gnome 2.26.

**Comment by doenietzomoeilijk** [comment] 2018-02-23 21:03
I can confirm this still occurs on Fedora 27, Gnome 3.26. Disabling the extension immediately lets me log out, having the extension active results in the SessionManager timeouts.

**Comment by kinduff** [comment] 2018-04-11 05:25
I can confirm this too with the caffeine extension, using Gnome 3.26 under Manjaro. Disabling solved the issue.

**Comment by jamesadney** [comment] 2018-04-11 18:18
I'm guessing this is a duplicate of #67. That bug has been fixed on master, but last time I checked it wasn't available from extensions.gnome.org. I installed the the extension manually ([instructions here](https://github.com/eonpatapon/gnome-shell-extension-caffeine#installation-from-git)) and it fixed the issue.

Ubuntu 17.10 with Gnome 3.26.2

**Comment by kinduff** [comment] 2018-04-11 19:10
I can confirm that the solution from @jamesadney works like a charm. Thank you!

**Comment by DougBeney** [comment] 2018-05-27 13:33
@jamesadney Thank you. Worked perfectly. Why wasn't an update pushed to extensions.gnome.org though? This seems like a very major issue.

**Comment by ET-Bent** [comment] 2018-06-21 13:17
DAMN I have been looking for a solution for this for ages. I would have never thought it was this tiny little awesome extension.... Man times of `sudo shutdown -P now` finally come to an end again!

**Comment by jonafato** [comment] 2019-11-29 19:07
This issue is fixed and should be closed.

**Closed** 2019-12-06 08:40 UTC
