### ISSUE TITLE
Error on upgrading on Gnome 3.38.1

### ISSUE THREAD

**Issue by the1derer** [eonpatapon/gnome-shell-extension-caffeine#169] opened 2020-11-23 13:13 UTC
I recently tried to upgrade in Pop! OS 20.10(Ubuntu 20.10) and got the following error.

```
The settings of extension caffeine@patapon.info had an error:
\```
Error: GSettings key control-nightlight not found in schema org.gnome.shell.extensions.caffeine
\```

Stack trace:
\```
_checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:580:23
createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:532:30
CaffeineWidget@/home/the1derer/.local/share/gnome-shell/extensions/caffeine@patapon.info/prefs.js:114:73
buildPrefsWidget@/home/the1derer/.local/share/gnome-shell/extensions/caffeine@patapon.info/prefs.js:296:20
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
\```

```

**Comment by pltnk** [comment] 2020-11-23 14:18
It just got fixed, see: https://github.com/eonpatapon/gnome-shell-extension-caffeine/issues/168

**Comment by eonpatapon** [comment] 2020-11-23 15:09
Duplicate of #168

Fixed in the latest version of e.g.o

**Closed by eonpatapon** 2020-11-23 15:09 UTC
