### ISSUE TITLE
Caffeine causes gnome-session-quit time out in GNOME 3.20

### ISSUE THREAD

**Issue by Jamesxu182** [eonpatapon/gnome-shell-extension-caffeine#67] opened 2016-05-06 11:20 UTC
### System Information
- Arch Linux
- Gnome 3.20
- Linux 4.18 LTS version
### Description

The issue only happened once when you first call power off button, and second time or more is fine.
- GUI
  
  if click "power off" button in control menu, which is located on the right-top of main screen, it will take long time (about 20 second) to start power off menu and I couldn't do nothing during this time but move cursor.
- Command-Line

Try to use command line to call the power off menu with "gnome-session-quit --power-off" in terminal to check the error information. it still take long time and only could move cursor.  the error message below:

``` sh
** (gnome-session-quit:26290): WARNING **: Failed to call Shutdown: Timeout was reached
```
- Repeat

To Repeat the issue, you need to reboot, re-login or restart gnome-shell (via alt+F2 then 'r'), click power off menu or input the command line.
- Screenshort
  - Command Line
    ![selection_031](https://cloud.githubusercontent.com/assets/7959510/15071366/ea40ac8c-1382-11e6-9b3a-a6af001f8433.png)
  - Power Off Button
    ![screenshot from 2016-05-06 12-18-38](https://cloud.githubusercontent.com/assets/7959510/15071583/9cc1d448-1384-11e6-99c2-869f720d286a.png)
  - Power Off Menu
    ![screenshot from 2016-05-06 12-16-02](https://cloud.githubusercontent.com/assets/7959510/15071593/a8447b22-1384-11e6-97dc-4a957b0a21b3.png)

GOOD LUCK

**Comment by Bujiraso** [comment] 2016-06-12 12:04
This appears to be a duplicate of #48, but it's a very pretty and well documented duplicate.
As I mentioned there, I can confirm this issue -- also running Arch, Gnome 3.20. The issue has existed since at least 3.16.

**Comment by Jamesxu182** [comment] 2016-06-12 12:15
Sorry for that, I didn't double check the existed issues before I created mine. I just report the issue I actually met as exact as I could to describle it.

Hope for debugging. Good luck!!!!

**Comment by postblue** [comment] 2016-07-13 12:44
Same error with:

* Arch Linux (without testing repositories)
* GNOME Shell 3.20.3
* commit c4f53ceb4f3502eee8a93ced8e386f91b1b8e700
* Linux 4.6.3
* systemd 230-5

and

* Debian Stretch
* GNOME Shell 3.20.3
* [gnome-shell-extension-caffeine](https://packages.debian.org/stretch/gnome-shell-extension-caffeine) package, seems like a patched 7b480f8a6867a56bf28007fdcd9cc901409f1796 (dated 20160328)
* Linux 4.6.3
* systemd 230-5

**Comment by ogjerstad** [comment] 2016-09-06 20:13
Also confirming this bug on Fedora 25, gnome 3.20. I have this problem even if caffeine is not used during the session, as long as the extension is enabled. I just now recently found out that is was related to caffeine. Don't remember if it existed in previous Fedora release.

**Comment by daniel-wtd** [comment] 2016-09-09 16:50
Hey,
can confirm this in F24/gnome 3.20.

Additionally to the mentioned error I can see:
```

Gjs-Message: JS LOG: gnome-session gave us a dead inhibitor: /org/gnome/SessionManager/Inhibitor49
Gjs-Message: JS LOG: gnome-session gave us a dead inhibitor: /org/gnome/SessionManager/Inhibitor48
Gjs-Message: JS LOG: Ignored exception from dbus method: Gio.IOErrorEnum: Timeout was reached
```

Regards

**Comment by dffischer** [comment] 2016-11-03 13:50
I maintain [the package of this extensions for Arch Linux](https://aur.archlinux.org/packages/gnome-shell-extension-caffeine-git/) and my users also report this error. I experienced it myself since at least gnome version 3.18 but failed to draw the connection any sooner. Different than @Jamesxu182, the power button from the menu always reacted instantly, but pressing *Ctrl*+*Alt*+*Del* yields the same delay. Repetition also requires a reboot.

**Comment by Bujiraso** [comment] 2016-11-04 22:01
+1 to @dffischer on repetition needing a reboot.
It only happens on the first attempt to power off.

**Comment by Bajoja** [comment] 2017-01-28 20:07
Same here on Gnome 3.22

**Comment by Skehmatics** [comment] 2017-02-18 06:08
Gnome 3.22, Ubuntu 16.10 here. 

Some quick testing shows that the bug only seems to be present when "Enable when a fullscreen application is running" is on.

Maybe caffeine could be seeing the overlay that gnome opens when logging out/restarting to be a "fullscreen" application? 

Can anyone else confirm?

**Comment by truongan** [comment] 2017-02-20 16:07
Any insights into this problem yet? Or at least where to look, anything additional information require?

**Comment by dreua** [comment] 2017-03-13 14:51
I am using https://github.com/jenspfahl/KeepAwake in the meantime. It has less features but as far as I know there are no annoying bugs.

**Comment by Th3Z0ne** [comment] 2017-05-12 22:53
Now as of gnome-shell 3.24.2 the bug that halts the shutdown menu from popping up in time also happens on the lock-screen; With caffeeine enabled (the extension itself) it takes about the 30s befor the machine is unlocked as it previously only did when trying to bring up the shutdown menu shown in the first post.

**Comment by janschulz** [comment] 2017-05-13 11:01
@Th3Z0ne Do you use System Monitor? Because the above symptoms (~2os delay after unlock window) look like https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/350, which is a problem of system monitor and mounted fuse drives.

**Comment by dffischer** [comment] 2017-05-13 11:12
Recently, my observations changed. The shutdown menu now appears instantaneously. I updated to gnome-shell 3.24 and switched to Wayland, but cannot tell which of both is more likely to have made the problem vanish.

As for the lock screen, I never experienced any problems whatsoever.

**Comment by Th3Z0ne** [comment] 2017-05-13 17:26
@janschulz thank you for pointing that out to me - i have to admit I was to fast blaming caffeine -.- I just tried to reproduce the fuse mount - but now no problems; Save to assume it was gnome-shell-system-monitor-applet as I have that also running. Thanks a lot for sure.

@dffischer for the freezing shutdown menu - I am on 3.24.2 under xorg and it still is there - my distro has not yet polished wayland out enough for me to sitch (e.g. icons missing and so on)

**Comment by hyphone** [comment] 2017-06-21 10:46
Fedora 25, Wayland

Because of this problem I didn't have it installed for the last couple of weeks.

The problem with the shutdown delay immediately came back (I'm using Wayland).

`Jun 21 12:37:37 powerbookG7 gnome-session[17092]: gnome-session-binary[17092]: WARNING: Client '/org/gnome/SessionManager/Client7' failed to reply before timeout
Jun 21 12:37:37 powerbookG7 gnome-session-binary[17092]: WARNING: Client '/org/gnome/SessionManager/Client7' failed to reply before timeout
Jun 21 12:37:37 powerbookG7 gnome-session[17092]: gnome-session-binary[17092]: WARNING: Client '/org/gnome/SessionManager/Client6' failed to reply before timeout
Jun 21 12:37:37 powerbookG7 gnome-session[17092]: gnome-session-binary[17092]: WARNING: Client '/org/gnome/SessionManager/Client5' failed to reply before timeout
Jun 21 12:37:37 powerbookG7 gnome-session[17092]: gnome-session-binary[17092]: WARNING: Client '/org/gnome/SessionManager/Client4' failed to reply before timeout
Jun 21 12:37:37 powerbookG7 gnome-session[17092]: gnome-session-binary[17092]: WARNING: Client '/org/gnome/SessionManager/Client2' failed to reply before timeout
Jun 21 12:37:37 powerbookG7 gnome-session[17092]: gnome-session-binary[17092]: WARNING: Client '/org/gnome/SessionManager/Client1' failed to reply before timeout
Jun 21 12:37:37 powerbookG7 gnome-session-binary[17092]: WARNING: Client '/org/gnome/SessionManager/Client6' failed to reply before timeout
Jun 21 12:37:37 powerbookG7 gnome-session[17092]: gnome-session-binary[17092]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 21 12:37:37 powerbookG7 gnome-session[17092]: gnome-session-binary[17092]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 21 12:37:37 powerbookG7 gnome-session[17092]: gnome-session-binary[17092]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 21 12:37:37 powerbookG7 gnome-session[17092]: gnome-session-binary[17092]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 21 12:37:37 powerbookG7 gnome-session[17092]: gnome-session-binary[17092]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 21 12:37:37 powerbookG7 gnome-session-binary[17092]: WARNING: Client '/org/gnome/SessionManager/Client5' failed to reply before timeout
Jun 21 12:37:37 powerbookG7 gnome-session-binary[17092]: WARNING: Client '/org/gnome/SessionManager/Client4' failed to reply before timeout
Jun 21 12:37:37 powerbookG7 gnome-session-binary[17092]: WARNING: Client '/org/gnome/SessionManager/Client2' failed to reply before timeout
Jun 21 12:37:37 powerbookG7 gnome-session-binary[17092]: WARNING: Client '/org/gnome/SessionManager/Client1' failed to reply before timeout
Jun 21 12:37:37 powerbookG7 gnome-session-binary[17092]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 21 12:37:37 powerbookG7 gnome-session-binary[17092]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 21 12:37:37 powerbookG7 gnome-session-binary[17092]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 21 12:37:37 powerbookG7 gnome-session-binary[17092]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 21 12:37:37 powerbookG7 gnome-session-binary[17092]: GLib-GObject-CRITICAL: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Jun 21 12:37:37 powerbookG7 gnome-shell[17148]: JS LOG: gnome-session gave us a dead inhibitor: /org/gnome/SessionManager/Inhibitor2
Jun 21 12:37:38 powerbookG7 gnome-session-binary[17092]: Entering running state`

**Comment by psuet** [comment] 2017-06-21 21:39
Ubuntu Gnome 16.04 exactly the same

**Comment by micealgallagher** [comment] 2017-06-30 14:04
Same. GNOME 3.24.2

**Comment by x0a** [comment] 2017-08-04 21:04
I'm also experiencing this problem

Ubuntu GNOME 17.04 
GNOME Shell 3.24.2

**Comment by srcnsahan** [comment] 2017-08-09 12:38
Same problem still exists when downloaded from extensions.gnome.org
Arch Linux
GNOME Shell 3.24.3

**Comment by x0a** [comment] 2017-08-09 13:58
I got the following response from emailing the maintainer:

> Hi,
> 
> I looked into it a bit, but I couldn't find the issue. Was able to
> reproduce it, but not all the time. But it's been a few years that I
> don't use g-s anymore so my interest of maintaining this extension has
> gone low.

The good news is that Power settings, specifically "Dim when inactive => Off" and "Blank screen => Never" is relaible enough that you don't need Caffeine to keep the screen on, if that's all you care about.

**Comment by tekstrong** [comment] 2017-08-09 15:29
On a related note, if you use the Argos extension ([https://github.com/p-e-w/argos](https://github.com/p-e-w/argos)) you can add your own script to toggle the settings that @x0a mentions above. I did away with Caffeine when Argos was released... which also did away with this bug.

**Comment by jurf** [comment] 2017-08-16 09:37
Fedora 26/Wayland, can confirm the problem.

**Comment by OliverLew** [comment] 2017-08-17 04:52
Same here with Archlinux

**Comment by unfulvio** [comment] 2017-08-30 03:19
Same issue here, appeared recently (not sure due to an extension update or system update)

* Ubuntu Gnome 17.04

**Comment by bepolymathe** [comment] 2017-09-20 09:47
Fedora 26, Wayland

Same issue here

**Comment by camabeh** [comment] 2017-09-27 11:19
Fedora 26, Wayland

Same problem

**Comment by Zlopez** [comment] 2017-11-17 14:00
Fedora 27, X11

Same issue

**Comment by robertdaleweir** [comment] 2017-11-22 18:22
I have used  [https://extensions.gnome.org/extension/1097/keep-awake/](url)  and so far so good.  I gave up on Caffeine as it is no longer being supported as far as I can see.  Not as cute but it works.

**Closed** 2017-12-29 11:46 UTC

**Comment by jurf** [comment] 2017-12-29 13:41
Thanks!

**Comment by slepkaviba** [comment] 2018-01-31 00:20
For me bug still occurs if caffeine is active (activated manually). All ok in auto mode.
