### ISSUE TITLE
Session Manager

### ISSUE THREAD

**Issue by mentofa123** [eonpatapon/gnome-shell-extension-caffeine#96] opened 2017-05-21 17:19 UTC
On Gnome 3.24 everytime i want to shutdown my PC via the Session manager on the Right in the Top bar, my PC freezes for 10 seconds. Maybe there is a fix for that

**Comment by eonpatapon** [comment] 2017-06-21 07:59
Duplicate of #48

**Closed by eonpatapon** 2017-06-21 07:59 UTC
