### ISSUE TITLE
Caffeine (v 54) causes a crash in Fedora 40

### ISSUE THREAD

**Issue by KhaaL** [eonpatapon/gnome-shell-extension-caffeine#329] opened 2024-05-07 20:07 UTC
I'm running Gnome 46 on Fedora 40, and Caffeine has been causing crashes when the plugin is installed, unactivated and the system is sent to suspend. 

This has been happening on kernels 6.8.7 and 6.8.8. What happened is that the previous gnome-session that I was logged into is not restored, but I begin with a new session. This happens 4 out of 5 times, so it was quite reproducible.

What gave away Caffeine was a entry in my System-D logs: journalctl output shows error 4 in libst (/usr/lib64/gnome-shell/libst-14.so):

```
kernel: gnome-shell[2293]: segfault at 55cc738f8 ip 00007f1678f0cb88 sp 00007ffec55eb730 error 4 in libst-14.so[7f1678edc000+5b000] likely on CPU 5 (core 1, socket 0)
                                               Module libgpg-error.so.0 from rpm libgpg-error-1.49-1.fc40.x86_64 
```

The issues stopped when the plugin was deactivated through extention manager.

**Comment by stuarthayhurst** [comment] 2024-05-07 21:25
This sounds like #268, the issue might be with `St` not Caffeine directly, it just happens to use `St`. Can you reproduce this with any other extensions that add an icon to the top bar?

**Comment by KhaaL** [comment] 2024-05-08 15:59
It might be a `st` bug, but I've only used Caffeine - I am restrictive on enabling too many extensions. 

Since my laptop is working well after disabling Caffeine, I'm not too eager to reproduce this bug with other plugins - I am satisfied with reporting it here.

**Comment by stuarthayhurst** [comment] 2024-06-27 20:12
Closing, since this is very likely an upstream issue that we can't do much about here, especially not without debug symbols and a larger back trace. If upstream debug this and determine it's an issue with Caffeine, feel free to reopen this :)

**Closed by stuarthayhurst** 2024-06-27 20:12 UTC
